(function(){
/* AI Bicep Generator — Chat / Form / Upload tabs */
const BicepPage = () => {
  const [tab, setTab] = useState('chat');
  return (
    <div className="page" style={{paddingBottom:0}}>
      <div className="page-header">
        <div>
          <h1 className="page-title">AI Bicep Delivery</h1>
          <p className="page-sub">Describe a deployment, upload a plan, or fill the form — get production-ready Bicep + a deploy script</p>
        </div>
        <div className="page-actions">
          <span className="pill accent"><Icon name="sparkles" size={10} />Aegis-7 model</span>
          <button className="btn"><Icon name="clock" size={14} />History</button>
        </div>
      </div>
      <div className="tabs">
        <button className={`tab ${tab==='chat'?'active':''}`} onClick={() => setTab('chat')}><Icon name="bot" size={12} style={{verticalAlign:'middle',marginRight:6}} />Chat</button>
        <button className={`tab ${tab==='form'?'active':''}`} onClick={() => setTab('form')}><Icon name="sliders" size={12} style={{verticalAlign:'middle',marginRight:6}} />Form Builder</button>
        <button className={`tab ${tab==='upload'?'active':''}`} onClick={() => setTab('upload')}><Icon name="upload" size={12} style={{verticalAlign:'middle',marginRight:6}} />From Plan</button>
      </div>
      {tab === 'chat' && <BicepChat />}
      {tab === 'form' && <BicepForm />}
      {tab === 'upload' && <BicepUpload />}
    </div>
  );
};

const BICEP_SAMPLE = `// generated by Aegis · 2026-05-04
targetScope = 'subscription'

@description('Environment short code')
param env string = 'prod'
@description('Primary deployment region')
param location string = 'westeurope'
@description('Resource prefix')
param prefix string = 'mer'

var tags = {
  costCenter: 'finops-erp'
  owner:      'platform@meridian.com'
  managedBy:  'aegis-cloud'
}

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name:     '\${prefix}-erp-\${env}-rg'
  location: location
  tags:     tags
}

module network 'modules/network.bicep' = {
  scope: rg
  name:  'network'
  params: {
    addressSpace: '10.40.0.0/16'
    location:     location
    tags:         tags
  }
}

module sql 'modules/sql.bicep' = {
  scope: rg
  name:  'sql-erp'
  params: {
    skuName:    'GP_Gen5_8'
    storageGB:  512
    geoRedundant: true
    location:   location
    tags:       tags
  }
}

module appService 'modules/appsvc.bicep' = {
  scope: rg
  name:  'app-erp'
  params: {
    skuTier:   'PremiumV3'
    instances: 3
    minTls:    '1.2'
    location:  location
    tags:      tags
  }
}

output rgId       string = rg.id
output sqlFqdn    string = sql.outputs.fqdn
output appUrl     string = appService.outputs.defaultHostname
`;

const colorize = (code) => {
  // Simple syntax highlighting — split by lines, regex-replace
  return code.split('\n').map((line, i) => {
    let out = line
      .replace(/(\/\/.*$)/g, '<span class="com">$1</span>')
      .replace(/(\b(?:targetScope|param|var|resource|module|output|string|int|bool|object|array|true|false)\b)/g, '<span class="kw">$1</span>')
      .replace(/('([^']+)')/g, '<span class="str">$1</span>')
      .replace(/\b(\d+(?:\.\d+)?)\b/g, '<span class="num">$1</span>');
    return <div key={i} dangerouslySetInnerHTML={{__html: out || '&nbsp;'}} />;
  });
};

const BicepChat = () => {
  const [msgs, setMsgs] = useState([
    { role: 'ai', text: "Hi Sarah — describe the deployment you want to generate. I can produce Bicep for migrations, new environments, policy assignments, or scaffolds. The more context (target tenant, region, SKU constraints), the better the output." },
    { role: 'user', text: "Generate Bicep for migrating Meridian Capital's on-prem ERP to West Europe. Need: VNet, Premium SQL with geo-redundancy, App Service P3 (3 instances), TLS 1.2, tagged for finops-erp cost center." },
    { role: 'ai', text: "Done. I've scaffolded a subscription-scoped deployment with three modules (network, sql, appsvc) and applied the policy guardrails I see for Meridian. Review on the right — I'll generate a deploy.sh that runs az deployment sub create with the right service principal." },
  ]);
  const [input, setInput] = useState('');
  const [busy, setBusy] = useState(false);
  const [showCode, setShowCode] = useState(true);
  const toast = useToast();
  const send = async () => {
    if (!input.trim() || busy) return;
    const text = input.trim();
    setMsgs(m => [...m, { role: 'user', text }]);
    setInput('');
    setBusy(true);
    setMsgs(m => [...m, { role: 'ai', text: '…thinking', pending: true }]);
    try {
      const reply = await window.claude.complete({
        messages: [{ role: 'user', content: `You are an Azure Bicep expert assistant. Respond concisely (3-4 sentences). Question: ${text}` }]
      });
      setMsgs(m => m.filter(x => !x.pending).concat({ role: 'ai', text: reply }));
    } catch (e) {
      setMsgs(m => m.filter(x => !x.pending).concat({ role: 'ai', text: "I've revised the template. Take a look at the Bicep panel — I added the changes you asked for and updated the parameter defaults." }));
    }
    setBusy(false);
  };
  const onCopy = () => { navigator.clipboard?.writeText(BICEP_SAMPLE); toast.push('Copied Bicep to clipboard'); };
  const onDeploy = () => toast.push('Deployment kicked off (dry-run)', 'ok');

  return (
    <div className="bicep-layout">
      <div className="bicep-pane">
        <div className="card-header">
          <div className="card-title">Conversation</div>
          <button className="btn btn-sm btn-ghost"><Icon name="plus" size={12} />New thread</button>
        </div>
        <div className="chat-msgs">
          {msgs.map((m, i) => (
            <div key={i} className={`chat-msg ${m.role}`}>
              <div className="msg-avatar">{m.role === 'ai' ? <Icon name="sparkles" size={13} /> : 'SC'}</div>
              <div className="msg-body">{m.pending ? <span className="dim">…thinking</span> : m.text}</div>
            </div>
          ))}
        </div>
        <div className="chat-input-wrap">
          <div className="chat-input">
            <button className="icon-btn" title="Attach"><Icon name="paperclip" size={14} /></button>
            <textarea value={input} onChange={e => setInput(e.target.value)}
              onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); } }}
              placeholder="Refine the deployment — e.g. 'add a Front Door with WAF in prevention mode'…" rows={1} />
            <button className="btn btn-primary btn-sm" onClick={send} disabled={busy}><Icon name="send" size={12} />Send</button>
          </div>
          <div className="row" style={{marginTop:8,gap:6,flexWrap:'wrap'}}>
            {['Add Front Door + WAF','Apply Meridian tags policy','Switch to UK South','Add private endpoints','Output deploy.sh'].map(s => (
              <button key={s} className="btn btn-sm" onClick={() => setInput(s)}>{s}</button>
            ))}
          </div>
        </div>
      </div>

      <div className="bicep-pane">
        <div className="card-header">
          <div className="row" style={{gap:10}}>
            <Icon name="code" size={14} className="dim" />
            <div>
              <div className="card-title mono">main.bicep</div>
              <div className="card-sub mono">subscription-scope · 89 lines · 3 modules</div>
            </div>
          </div>
          <div className="row" style={{gap:6}}>
            <button className="btn btn-sm" onClick={() => setShowCode(!showCode)}>{showCode ? 'Diagram' : 'Code'}</button>
            <button className="btn btn-sm" onClick={onCopy}><Icon name="copy" size={12} />Copy</button>
            <button className="btn btn-sm"><Icon name="download" size={12} />Download .zip</button>
            <button className="btn btn-sm btn-primary" onClick={onDeploy}><Icon name="play" size={12} />Deploy</button>
          </div>
        </div>
        {showCode ? (
          <div className="code-block">{colorize(BICEP_SAMPLE)}</div>
        ) : (
          <BicepDiagram />
        )}
      </div>
    </div>
  );
};

const BicepDiagram = () => (
  <div style={{padding:24,height:'100%',overflow:'auto',display:'flex',flexDirection:'column',gap:14}}>
    <div style={{textAlign:'center'}}>
      <div className="pill accent" style={{display:'inline-flex'}}><Icon name="cloud" size={11} />Subscription · Meridian Capital prod</div>
    </div>
    <DiagramRG label="mer-erp-prod-rg" location="West Europe">
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:10}}>
        <DiagramNode icon="globe" name="VNet" sub="10.40.0.0/16" />
        <DiagramNode icon="database" name="SQL Premium" sub="GP_Gen5_8 · Geo" />
        <DiagramNode icon="cloud" name="App Service" sub="P3 · 3 instances" />
      </div>
    </DiagramRG>
    <div style={{textAlign:'center',color:'var(--text-muted)',fontSize:11,marginTop:8}}>
      <Icon name="check" size={11} style={{verticalAlign:'middle',color:'var(--ok)'}} /> Validated against Meridian's policy assignments — TLS 1.2, geo-redundancy, required tags ✓
    </div>
  </div>
);

const DiagramRG = ({ label, location, children }) => (
  <div style={{border:'1.5px dashed var(--border-strong)',borderRadius:10,padding:14}}>
    <div style={{display:'flex',justifyContent:'space-between',marginBottom:10,fontSize:12}}>
      <span className="mono" style={{fontWeight:600}}>{label}</span>
      <span className="muted">{location}</span>
    </div>
    {children}
  </div>
);

const DiagramNode = ({ icon, name, sub }) => (
  <div style={{padding:'12px 10px',border:'1px solid var(--border)',borderRadius:8,background:'var(--bg-elev-2)',textAlign:'center'}}>
    <Icon name={icon} size={20} style={{color:'var(--accent)',marginBottom:4}} />
    <div style={{fontSize:12,fontWeight:500}}>{name}</div>
    <div className="mono dim" style={{fontSize:10,marginTop:2}}>{sub}</div>
  </div>
);

const BicepForm = () => {
  const [services, setServices] = useState({ vm: true, sql: true, storage: false, appsvc: true, kv: false, aks: false });
  const [region, setRegion] = useState('West Europe');
  const [env, setEnv] = useState('prod');
  return (
    <div className="bicep-layout">
      <div className="bicep-pane" style={{padding:20,overflow:'auto'}}>
        <h3 style={{margin:'0 0 12px',fontSize:13,textTransform:'uppercase',letterSpacing:'.04em',color:'var(--text-muted)'}}>Deployment</h3>
        <div className="col" style={{gap:10,marginBottom:24}}>
          <div className="row" style={{gap:10}}>
            <label style={{flex:1}}>
              <div style={{fontSize:11,color:'var(--text-muted)',marginBottom:4}}>Tenant</div>
              <select className="select" style={{width:'100%'}}><option>Meridian Capital</option><option>Northwind Logistics</option></select>
            </label>
            <label style={{flex:1}}>
              <div style={{fontSize:11,color:'var(--text-muted)',marginBottom:4}}>Environment</div>
              <select className="select" style={{width:'100%'}} value={env} onChange={e=>setEnv(e.target.value)}>
                <option>prod</option><option>staging</option><option>dev</option>
              </select>
            </label>
          </div>
          <label>
            <div style={{fontSize:11,color:'var(--text-muted)',marginBottom:4}}>Region</div>
            <select className="select" style={{width:'100%'}} value={region} onChange={e=>setRegion(e.target.value)}>
              {window.AegisData.REGIONS.map(r => <option key={r}>{r}</option>)}
            </select>
          </label>
          <label>
            <div style={{fontSize:11,color:'var(--text-muted)',marginBottom:4}}>Resource group prefix</div>
            <input className="input" style={{width:'100%'}} defaultValue="mer-erp" />
          </label>
        </div>

        <h3 style={{margin:'0 0 12px',fontSize:13,textTransform:'uppercase',letterSpacing:'.04em',color:'var(--text-muted)'}}>Services</h3>
        <div className="col" style={{gap:6,marginBottom:20}}>
          {[
            ['vm','Virtual Machines','cpu'],
            ['sql','SQL Database','database'],
            ['storage','Storage Account','database'],
            ['appsvc','App Service','cloud'],
            ['kv','Key Vault','lock'],
            ['aks','AKS Cluster','layers'],
          ].map(([key,label,icon]) => (
            <label key={key} style={{display:'flex',alignItems:'center',gap:10,padding:10,borderRadius:6,border:'1px solid var(--border)',cursor:'pointer',background: services[key] ? 'var(--bg-hover)' : 'transparent'}}>
              <input type="checkbox" checked={services[key]} onChange={() => setServices(s => ({...s, [key]: !s[key]}))} />
              <Icon name={icon} size={14} className="dim" />
              <span style={{fontSize:13}}>{label}</span>
            </label>
          ))}
        </div>

        <h3 style={{margin:'0 0 12px',fontSize:13,textTransform:'uppercase',letterSpacing:'.04em',color:'var(--text-muted)'}}>Guardrails</h3>
        <div className="col" style={{gap:6}}>
          <label className="row" style={{gap:8,fontSize:12}}><input type="checkbox" defaultChecked /><span>Enforce TLS 1.2 minimum</span></label>
          <label className="row" style={{gap:8,fontSize:12}}><input type="checkbox" defaultChecked /><span>Required tags (cost-center, owner)</span></label>
          <label className="row" style={{gap:8,fontSize:12}}><input type="checkbox" defaultChecked /><span>Diagnostic logs enabled</span></label>
          <label className="row" style={{gap:8,fontSize:12}}><input type="checkbox" /><span>Private endpoints only</span></label>
        </div>

        <button className="btn btn-primary" style={{marginTop:24,width:'100%'}}><Icon name="sparkles" size={14} />Generate Bicep</button>
      </div>
      <div className="bicep-pane">
        <div className="card-header">
          <div className="card-title mono">main.bicep</div>
          <button className="btn btn-sm"><Icon name="copy" size={12} />Copy</button>
        </div>
        <div className="code-block">{colorize(BICEP_SAMPLE)}</div>
      </div>
    </div>
  );
};

const BicepUpload = () => {
  const [file, setFile] = useState(null);
  return (
    <div className="bicep-layout">
      <div className="bicep-pane" style={{padding:24,display:'flex',flexDirection:'column'}}>
        <div style={{flex:1,border:'1.5px dashed var(--border-strong)',borderRadius:10,display:'grid',placeItems:'center',padding:40,textAlign:'center'}}>
          {file ? (
            <div>
              <Icon name="file-text" size={32} style={{color:'var(--accent)',marginBottom:12}} />
              <div style={{fontSize:14,fontWeight:500,marginBottom:4}}>{file}</div>
              <div className="muted" style={{fontSize:12,marginBottom:16}}>Parsing diagram and resource references…</div>
              <div className="bar" style={{width:200,margin:'0 auto'}}><span style={{width:'68%'}} /></div>
              <div className="row" style={{gap:8,justifyContent:'center',marginTop:20}}>
                <button className="btn btn-sm" onClick={() => setFile(null)}>Cancel</button>
              </div>
            </div>
          ) : (
            <div>
              <Icon name="upload" size={32} className="dim" />
              <div style={{fontSize:14,fontWeight:500,margin:'12px 0 4px'}}>Drop a deployment plan</div>
              <div className="muted" style={{fontSize:12,marginBottom:16}}>Visio (.vsdx), draw.io, PDF, or markdown · Aegis parses entities and produces Bicep</div>
              <button className="btn btn-primary" onClick={() => setFile('migration-plan-erp.vsdx')}><Icon name="upload" size={14} />Choose file</button>
            </div>
          )}
        </div>
        <div style={{fontSize:11,color:'var(--text-muted)',marginTop:14}}>
          <strong style={{color:'var(--text)'}}>Tip:</strong> include resource counts, regions, and SLAs in your plan. The cleaner the input, the closer the Bicep output is to production-ready.
        </div>
      </div>
      <div className="bicep-pane">
        <div className="card-header">
          <div className="card-title">Parsed Output</div>
          <span className="pill">{file ? 'In progress' : 'Awaiting upload'}</span>
        </div>
        <div className="card-body" style={{height:'100%'}}>
          {file ? (
            <div className="col">
              <div className="row" style={{gap:8}}><Icon name="check" size={12} style={{color:'var(--ok)'}} /><span style={{fontSize:13}}>Identified <strong>3 resource groups</strong> across 2 regions</span></div>
              <div className="row" style={{gap:8}}><Icon name="check" size={12} style={{color:'var(--ok)'}} /><span style={{fontSize:13}}>Detected <strong>14 services</strong> (12 supported)</span></div>
              <div className="row" style={{gap:8}}><Icon name="alert-triangle" size={12} style={{color:'var(--warn)'}} /><span style={{fontSize:13}}><strong>2 ambiguities</strong> — confirm SKU for "DB cluster"</span></div>
              <div className="row" style={{gap:8}}><Icon name="clock" size={12} className="dim" /><span style={{fontSize:13,color:'var(--text-muted)'}}>Generating Bicep modules…</span></div>
            </div>
          ) : (
            <div className="empty"><Icon name="file-text" size={24} /><p style={{marginTop:8}}>Upload a plan to see parsed output here.</p></div>
          )}
        </div>
      </div>
    </div>
  );
};

window.BicepPage = BicepPage;

})();
